/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Danimen
 */
public class Kuis2 extends javax.swing.JFrame {

    /**
     * Creates new form Kuis2
     */
    public Kuis2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tb1 = new javax.swing.JTextField();
        tb2 = new javax.swing.JTextField();
        tb3 = new javax.swing.JTextField();
        tb4 = new javax.swing.JTextField();
        tb5 = new javax.swing.JTextField();
        proses = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TA = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(tb1);
        tb1.setBounds(70, 20, 250, 30);
        getContentPane().add(tb2);
        tb2.setBounds(70, 70, 250, 30);
        getContentPane().add(tb3);
        tb3.setBounds(70, 120, 250, 30);

        tb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb4ActionPerformed(evt);
            }
        });
        getContentPane().add(tb4);
        tb4.setBounds(70, 170, 250, 30);

        tb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb5ActionPerformed(evt);
            }
        });
        getContentPane().add(tb5);
        tb5.setBounds(70, 220, 250, 30);

        proses.setText("Proses");
        proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesActionPerformed(evt);
            }
        });
        getContentPane().add(proses);
        proses.setBounds(60, 270, 65, 23);

        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus);
        hapus.setBounds(160, 270, 63, 23);

        keluar.setText("Keluar");
        getContentPane().add(keluar);
        keluar.setBounds(250, 270, 63, 23);

        jLabel1.setText("Harga 1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 20, 70, 30);

        jLabel2.setText("Harga 2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 70, 60, 30);

        jLabel3.setText("Harga 3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 120, 60, 30);

        jLabel4.setText("Harga 4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 170, 50, 30);

        jLabel5.setText("Diskon");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 220, 50, 30);

        TA.setColumns(20);
        TA.setRows(5);
        jScrollPane1.setViewportView(TA);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 320, 260, 96);

        setBounds(0, 0, 365, 461);
    }// </editor-fold>//GEN-END:initComponents

    private void tb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tb4ActionPerformed

    private void tb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tb5ActionPerformed

    private void prosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesActionPerformed
       int harga1 = Integer.parseInt(tb1.getText());
       int harga2 = Integer.parseInt(tb2.getText());
       int harga3 = Integer.parseInt(tb3.getText());
       int harga4 = Integer.parseInt(tb4.getText());
       int diskon = Integer.parseInt(tb5.getText());
       
       int total_harga = harga1+harga2+harga3+harga4;
       int disc = total_harga * diskon / 100;
       int total_bayar = total_harga - diskon;
       TA.setText("Harga Barang 1: "+harga1+"\nHarga Barang 2 :"+harga2+"\nHarga Barang 3: "+harga3+"\nHarga Barang 4 : "
               +harga4+"\nDiskon : "+diskon+"\nTotal Bayar : " +total_bayar);
       
    }//GEN-LAST:event_prosesActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
      tb1.setText(" ");
      tb2.setText(" ");
      tb3.setText(" ");
      tb4.setText(" ");
      tb5.setText(" ");
      TA.setText("");
      
    }//GEN-LAST:event_hapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kuis2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TA;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton keluar;
    private javax.swing.JButton proses;
    private javax.swing.JTextField tb1;
    private javax.swing.JTextField tb2;
    private javax.swing.JTextField tb3;
    private javax.swing.JTextField tb4;
    private javax.swing.JTextField tb5;
    // End of variables declaration//GEN-END:variables
}
