/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Danimen
 */
public class lat3 extends javax.swing.JFrame {

    /**
     * Creates new form lat3
     */
    public lat3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bil1 = new javax.swing.JTextField();
        bil2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Btnkali = new javax.swing.JButton();
        Btnbagi = new javax.swing.JButton();
        btntambah = new javax.swing.JButton();
        Btnkurang = new javax.swing.JButton();
        Hasil = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(bil1);
        bil1.setBounds(110, 60, 150, 30);
        getContentPane().add(bil2);
        bil2.setBounds(110, 110, 150, 30);

        jLabel1.setText("KALKULATOR SEDERHANA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 10, 260, 30);

        jLabel2.setText("Bilangan 1");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 60, 90, 30);

        jLabel3.setText("Bilangan 2");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 104, 60, 30);

        Btnkali.setText("X");
        Btnkali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnkaliActionPerformed(evt);
            }
        });
        getContentPane().add(Btnkali);
        Btnkali.setBounds(60, 180, 50, 30);

        Btnbagi.setText(":");
        Btnbagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnbagiActionPerformed(evt);
            }
        });
        getContentPane().add(Btnbagi);
        Btnbagi.setBounds(140, 180, 50, 30);

        btntambah.setText("+");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });
        getContentPane().add(btntambah);
        btntambah.setBounds(220, 180, 50, 30);

        Btnkurang.setText("-");
        Btnkurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnkurangActionPerformed(evt);
            }
        });
        getContentPane().add(Btnkurang);
        Btnkurang.setBounds(290, 180, 50, 30);

        Hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HasilActionPerformed(evt);
            }
        });
        getContentPane().add(Hasil);
        Hasil.setBounds(110, 250, 160, 50);

        jLabel4.setText("Operator");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(170, 140, 80, 30);

        jLabel5.setText("Hasil");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(180, 220, 60, 20);

        setBounds(0, 0, 416, 351);
    }// </editor-fold>//GEN-END:initComponents

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
      double bilangan1 = Double.parseDouble(bil1.getText());
      double bilangan2 = Double.parseDouble(bil2.getText());
      double hasil = bilangan1 + bilangan2;
      Hasil.setText(String.valueOf(hasil));
    }//GEN-LAST:event_btntambahActionPerformed

    private void BtnkurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnkurangActionPerformed
      double bilangan1 = Double.parseDouble(bil1.getText());
      double bilangan2 = Double.parseDouble(bil2.getText());
      double hasil = bilangan1 - bilangan2;
      Hasil.setText(String.valueOf(hasil));
    }//GEN-LAST:event_BtnkurangActionPerformed

    private void HasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HasilActionPerformed

    private void BtnkaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnkaliActionPerformed
        int bilangan1 = Integer.parseInt(bil1.getText());
        int bilangan2 = Integer.parseInt(bil2.getText());
        int hasil = bilangan1 * bilangan2;
        Hasil.setText(String.valueOf(hasil));
        
    }//GEN-LAST:event_BtnkaliActionPerformed

    private void BtnbagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnbagiActionPerformed
      double bilangan1 = Double.parseDouble(bil1.getText());
      double bilangan2 = Double.parseDouble(bil2.getText());
      double hasil = bilangan1 / bilangan2;
      Hasil.setText(String.valueOf(hasil));
    }//GEN-LAST:event_BtnbagiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lat3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lat3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lat3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lat3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lat3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btnbagi;
    private javax.swing.JButton Btnkali;
    private javax.swing.JButton Btnkurang;
    private javax.swing.JTextField Hasil;
    private javax.swing.JTextField bil1;
    private javax.swing.JTextField bil2;
    private javax.swing.JButton btntambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
